//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedRecSystem.Admin
{
    public partial class ManageAppointments
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// GridView1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridView1;

        /// <summary>
        /// hiddenID control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hiddenID;

        /// <summary>
        /// txtName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtName;

        /// <summary>
        /// txtAge control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAge;

        /// <summary>
        /// txtGender control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtGender;

        /// <summary>
        /// txtContact control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContact;

        /// <summary>
        /// btnUpdate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUpdate;
    }
}
